services:
  controller-1:
    image: apache/kafka:3.8.0
    container_name: controller-1
    hostname: controller-1
    networks:
      - net
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - controller-1-data:/var/lib/kafka/data
      - controller-1-secrets:/etc/kafka/secrets
      - controller-1-config:/mnt/shared/config

  controller-2:
    image: apache/kafka:3.8.0
    container_name: controller-2
    hostname: controller-2
    networks:
      - net
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - controller-2-data:/var/lib/kafka/data
      - controller-2-secrets:/etc/kafka/secrets
      - controller-2-config:/mnt/shared/config

  controller-3:
    image: apache/kafka:3.8.0
    container_name: controller-3
    hostname: controller-3
    networks:
      - net
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - controller-3-data:/var/lib/kafka/data
      - controller-3-secrets:/etc/kafka/secrets
      - controller-3-config:/mnt/shared/config

  broker-1:
    image: apache/kafka:3.8.0
    container_name: broker-1
    hostname: broker-1
    networks:
      - net
    ports:
      - 29092:9092
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'BROKER://:19092,CLIENT://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'BROKER://broker-1:19092,CLIENT://localhost:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,CLIENT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - broker-1-data:/var/lib/kafka/data
      - broker-1-secrets:/etc/kafka/secrets
      - broker-1-config:/mnt/shared/config
    depends_on:
      - controller-1
      - controller-2
      - controller-3

  broker-2:
    image: apache/kafka:3.8.0
    container_name: broker-2
    hostname: broker-2
    networks:
      - net
    ports:
      - 39092:9092
    environment:
      KAFKA_NODE_ID: 5
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'BROKER://:19092,CLIENT://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'BROKER://broker-2:19092,CLIENT://localhost:39092'
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,CLIENT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - broker-2-data:/var/lib/kafka/data
      - broker-2-secrets:/etc/kafka/secrets
      - broker-2-config:/mnt/shared/config
    depends_on:
      - controller-1
      - controller-2
      - controller-3

  broker-3:
    image: apache/kafka:3.8.0
    container_name: broker-3
    hostname: broker-3
    networks:
      - net
    ports:
      - 49092:9092
    environment:
      KAFKA_NODE_ID: 6
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'BROKER://:19092,CLIENT://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'BROKER://broker-3:19092,CLIENT://localhost:49092'
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,CLIENT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - broker-3-data:/var/lib/kafka/data
      - broker-3-secrets:/etc/kafka/secrets
      - broker-3-config:/mnt/shared/config
    depends_on:
      - controller-1
      - controller-2
      - controller-3

volumes:
  controller-1-data:
  controller-1-secrets:
  controller-1-config:

  controller-2-data:
  controller-2-secrets:
  controller-2-config:

  controller-3-data:
  controller-3-secrets:
  controller-3-config:

  broker-1-data:
  broker-1-secrets:
  broker-1-config:

  broker-2-data:
  broker-2-secrets:
  broker-2-config:

  broker-3-data:
  broker-3-secrets:
  broker-3-config:

networks:
  net:
